development:
  host: localhost
  database: mysenso_development

test:
  host: localhost
  database: mysenso_test

# set these environment variables on your prod server
production:
  host: staff.mongohq.com
  port: 10082
  username: heroku
  password: 4885870
  database: app1051709
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
